#!/usr/bin/bash

# script to run prism launcher on a bwrap sandbox because i don't trust some random minecraft mods lol
# and i don't want to use flatpak prism launcher

exec bwrap \
    --unshare-user \
    --unshare-ipc \
    --unshare-pid \
    --unshare-uts \
    --unshare-cgroup \
    --die-with-parent \
    --dev /dev \
    --proc /proc \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/bin /usr/bin \
    --ro-bind /etc /etc \
    --ro-bind /usr/share /usr/share \
    --symlink usr/lib /lib \
    --symlink usr/lib64 /lib64 \
    --symlink usr/bin /bin \
    --symlink usr/bin /sbin \
    --symlink /usr/lib /usr/lib64 \
    --dev-bind-try /dev/dri /dev/dri \
    --ro-bind-try /sys/dev/char /sys/dev/char \
    --ro-bind-try /sys/devices /sys/devices \
    --ro-bind-try /run/dbus /run/dbus \
    --ro-bind-try "/run/user/$UID/pipewire-0" "/run/user/$UID/pipewire-0" \
    --ro-bind-try /run/user/$UID/pulse /run/user/$UID/pulse \
    --bind-try "/run/user/$UID/discord-ipc-0" /run/user/$UID/discord-ipc-0 \
    --ro-bind-try /run/user/$UID/$WAYLAND_DISPLAY /run/user/$UID/$WAYLAND_DISPLAY \
    --ro-bind-try /run/user/$UID/bus /run/user/$UID/bus \
    --setenv XDG_RUNTIME_DIR "/run/user/$UID" \
    --setenv DBUS_SESSION_BUS_ADDRESS "unix:path=/run/user/$UID/bus" \
    --setenv XCURSOR_THEME breeze_cursors \
    --setenv PATH /usr/bin:$HOME/.local/bin/ \
    --tmpfs /tmp \
    --ro-bind-try $HOME/.Xauthority $HOME/.Xauthority \
    --ro-bind-try $XAUTHORITY $XAUTHORITY \
    --ro-bind-try $HOME/.Xdefaults $HOME/.Xdefaults \
    --ro-bind-try $HOME/.Xresources $HOME/.Xresources \
    --ro-bind-try $HOME/.config/gamemode.ini $HOME/.config/gamemode.ini \
    --ro-bind-try $HOME/.config/kdeglobals $HOME/.config/kdeglobals \
    --ro-bind-try $HOME/.config/breezerc $HOME/.config/breezerc \
    --ro-bind-try $HOME/.config/klassyrc $HOME/.config/klassyrc \
    --ro-bind-try $HOME/.config/qt5ct $HOME/.config/qt5ct \
    --ro-bind-try /tmp/.X11-unix /tmp/.X11-unix \
    --ro-bind-try /usr/lib/snapd-xdg-open/xdg-open /usr/bin/xdg-open \
    --ro-bind-try /usr/lib/snapd-xdg-open/xdg-open /usr/bin/firefox \
    --ro-bind-try /usr/lib/snapd-xdg-open/xdg-open /usr/bin/dolphin \
    --setenv ALSOFT_DRIVERS pulse \
    --bind-try $HOME/Games/PrismLauncher $HOME/Games/PrismLauncher \
    --bind-try $HOME/.local/share/PrismLauncher $HOME/.local/share/PrismLauncher \
    --ro-bind-try $HOME/.local/bin/instancesandbox $HOME/.local/bin/instancesandbox \
    --bind-try $HOME/.cache/PrismLauncher $HOME/.cache \
    /usr/bin/prismlauncher "$@"
